# Generated by Django 5.2.14 on 2026-08-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0014_contact_deleted_at_contact_is_deleted'),
        ('treks_app', '0015_contact_deleted_at_contact_is_deleted_and_more'),
    ]

    operations = [
    ]
