# Generated by Django 5.2.14 on 2026-08-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0016_merge_20260819_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetytip',
            name='section_title',
            field=models.CharField(default='Safety Tips', max_length=200),
        ),
    ]
