# Generated by Django 5.2.14 on 2026-08-19 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0017_safetytip_section_title'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='testimonial',
            name='trek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='treks_app.treklist'),
        ),
        migrations.DeleteModel(
            name='TrekCategory',
        ),
        migrations.DeleteModel(
            name='Trek',
        ),
    ]
