# Generated by Django 6.1.1 on 2026-09-16 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0018_remove_trek_additional_images_remove_trek_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(editable=False, max_length=40, unique=True)),
                ('platform', models.CharField(choices=[('web', 'Public website (React)'), ('admin', 'Admin panel (browser)'), ('backend', 'Backend (Django)')], max_length=10)),
                ('severity', models.CharField(choices=[('fatal', 'Fatal'), ('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], default='error', max_length=10)),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField(blank=True)),
                ('route', models.CharField(blank=True, help_text='Page URL or API path where this happened', max_length=500)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('app_version', models.CharField(blank=True, max_length=40)),
                ('extra_context', models.JSONField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['platform', 'severity'], name='treks_app_c_platfor_792cc2_idx'), models.Index(fields=['is_resolved'], name='treks_app_c_is_reso_1cad55_idx'), models.Index(fields=['created_at'], name='treks_app_c_created_23792e_idx')],
            },
        ),
    ]
