import DOMPurify from 'dompurify';
import useApi from '../../hooks/useApi';
import '../../styles/Legal.css';

// Layout for the legal pages, set as a formal document (not a card): a
// centred title block, the electronic-record notice, then the fixed legal
// text (children) followed by any extra sections added from the Django
// admin. `numberSection(i)` continues the document's own numbering. A page
// without a `contentKind` (the Refund Policy) has no admin sections, so
// nothing is requested.
export default function LegalPage({ title, audience, updated, contentKind, numberSection, children }) {
  const { data } = useApi(contentKind ? `/api/content-sections/${contentKind}/` : null);
  const extraSections = Array.isArray(data) ? data : [];

  return (
    <div className="page legal-page">
      <div className="container">
        <article className="legal-doc">
          <header className="legal-doc__header">
            <p className="legal-doc__brand">Aorbo Treks</p>
            <h1 className="legal-doc__title">{title}</h1>
            {audience && <p className="legal-doc__audience">{audience}</p>}
            {updated && <p className="legal-doc__meta">Last updated: {updated}</p>}
          </header>

          <p className="legal-doc__notice">
            This document is an electronic record under the Information Technology Act, 2000 and the rules made
            under it. It is generated by a computer system and does not need a physical or digital signature.
          </p>

          <div className="legal">
            {children}
            {extraSections.map((section, i) => (
              <section key={section.id}>
                <h3>{numberSection(i)}. {section.heading}</h3>
                {section.sub_heading && <h4>{section.sub_heading}</h4>}
                <div dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(section.content) }} />
              </section>
            ))}
          </div>
        </article>
      </div>
    </div>
  );
}
