# Generated by Django 6.1.1 on 2026-09-16 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditChainLock',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('rank', models.SmallIntegerField(default=100, help_text='Lower = more powerful. super_admin = 0.')),
                ('is_system', models.BooleanField(default=False, help_text='Seeded roles that must not be deleted/renamed via the UI.')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='StaffPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='resource:action, e.g. treks:edit', max_length=80, unique=True)),
                ('resource', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=30)),
                ('category', models.CharField(help_text='UI grouping', max_length=40)),
                ('label', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_dangerous', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='AccessAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(unique=True)),
                ('actor_type', models.CharField(default='staff', max_length=20)),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('actor_name', models.CharField(blank=True, max_length=120, null=True)),
                ('actor_role', models.CharField(blank=True, max_length=40, null=True)),
                ('actor_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('actor_ua', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(max_length=50)),
                ('resource_type', models.CharField(blank=True, max_length=50, null=True)),
                ('resource_id', models.CharField(blank=True, max_length=64, null=True)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('http_method', models.CharField(blank=True, max_length=8, null=True)),
                ('route', models.CharField(blank=True, max_length=255, null=True)),
                ('status_code', models.SmallIntegerField(blank=True, null=True)),
                ('prev_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['actor_id'], name='access_cont_actor_i_98b108_idx'), models.Index(fields=['resource_type', 'resource_id'], name='access_cont_resourc_b4a80f_idx'), models.Index(fields=['action'], name='access_cont_action_719c63_idx'), models.Index(fields=['created_at'], name='access_cont_created_5038c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffMfa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totp_secret', models.TextField(blank=True, help_text='AES-GCM encrypted', null=True)),
                ('pending_secret', models.TextField(blank=True, help_text='encrypted; set during enrollment, before verify', null=True)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('backup_codes', models.JSONField(blank=True, help_text='[{hash, used_at}]', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_code_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('recovery_reset_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recovery_reset_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='access_control.role')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_grants', to='access_control.staffpermission')),
            ],
            options={
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', through='access_control.RolePermission', to='access_control.staffpermission'),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('locked', 'Locked')], default='active', max_length=10)),
                ('session_version', models.PositiveIntegerField(default=1)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('account_locked_until', models.DateTimeField(blank=True, null=True)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='access_control.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='sha256', max_length=64, unique=True)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.CharField(choices=[('grant', 'Grant'), ('revoke', 'Revoke')], default='grant', max_length=6)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overrides', to='access_control.staffpermission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'permission')},
            },
        ),
    ]
