# Generated by Django 6.1.1 on 2026-09-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSerialCounter',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='staff_serial',
            field=models.CharField(default='', editable=False, help_text='Auto-assigned sequential ID, e.g. AORBO00001. Never reused, even if the account is later deleted.', max_length=20, unique=True),
        ),
    ]
