"""
Django settings for aorbo_project.

Generated by 'django-admin startproject' using Django 5.0.1.
For more information, see https://docs.djangoproject.com/en/5.0/topics/settings/
"""

import os
from pathlib import Path
import sys
from decouple import config

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = config('SECRET_KEY')

DEBUG = config('DEBUG', default='False', cast=lambda x: x.lower() in ('true', '1', 'yes'))

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1,16.170.247.251',
    cast=lambda x: [i.strip() for i in x.split(',')]
)

CSRF_TRUSTED_ORIGINS = [
    "https://aorbotreks.com",
    "https://www.aorbotreks.com",
]

if DEBUG:
    CSRF_TRUSTED_ORIGINS += [
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ]

# HSTS prevents downgrade attacks, X-Frame prevents clickjacking, etc.
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
REFERRER_POLICY = 'strict-origin-when-cross-origin'
X_FRAME_OPTIONS = 'DENY'

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Strict'
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Strict'

# The only thing using sessions on this site is the staff admin panel (the
# public frontend is a separate stateless SPA), so a short admin-appropriate
# lifetime is safe globally. Django's own defaults (2 weeks, survives browser
# close) are far too long for an admin session.
SESSION_COOKIE_AGE = 60 * 60 * 12  # 12 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True  # sliding expiry while actively working

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'corsheaders',
    'rest_framework',
    'csp',
    'axes',
    'access_control',
    'treks_app',
    'ckeditor',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'access_control.middleware.StaffSessionValidationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
    'treks_app.middleware.BackendCrashLoggingMiddleware',
    'axes.middleware.AxesMiddleware',
]

# CORS
CORS_ORIGIN_ALLOW_ALL = False

CORS_ALLOWED_ORIGINS = [
    "https://aorbotreks.com",
    "https://www.aorbotreks.com",
]

if DEBUG:
    CORS_ALLOWED_ORIGINS += [
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ]

# Lets a deployment that isn't on its final domain yet (e.g. a bare VPS IP)
# allow its own origin without hardcoding that temporary value into source.
_EXTRA_ORIGINS = config(
    'EXTRA_ALLOWED_ORIGINS',
    default='',
    cast=lambda x: [i.strip() for i in x.split(',') if i.strip()],
)
CORS_ALLOWED_ORIGINS += _EXTRA_ORIGINS
CSRF_TRUSTED_ORIGINS += _EXTRA_ORIGINS

CORS_ALLOW_CREDENTIALS = True

# Rate limiting with django-axes
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1
AXES_LOCKOUT_TEMPLATE = 'registration/lockout.html'
AXES_LOCKOUT_URL = '/locked/'
AXES_IP_WHITELIST = []
AXES_ENABLE_ACCESS_LOG = True
AXES_ENABLED = True
ROOT_URLCONF = 'aorbo_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aorbo_project.wsgi.application'

# Database - Supabase PostgreSQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}

if not DEBUG and 'runserver' not in sys.argv:
    # Deployments served over plain HTTP only (e.g. bare IP, no TLS/domain yet)
    # must opt out of the HTTPS redirect and secure-cookie flags, or every
    # request loops/fails since there is no TLS listener to redirect to.
    FORCE_SSL = config('FORCE_SSL', default='True', cast=lambda x: x.lower() in ('true', '1', 'yes'))
    SECURE_SSL_REDIRECT = FORCE_SSL
    SESSION_COOKIE_SECURE = FORCE_SSL
    CSRF_COOKIE_SECURE = FORCE_SSL
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'access_control.backends.StaffLockoutBackend',
]

# Argon2id first so Django transparently re-hashes any legacy PBKDF2 password
# to Argon2id the next time that user logs in successfully (built into
# django.contrib.auth.hashers.check_password's setter callback).
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

PASSWORD_RESET_FORM = 'treks_app.forms.CustomPasswordResetForm'

EMAIL_BACKEND = config("EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT", cast=int)
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

ADMINS = [
    ('', config('ADMIN_EMAIL_1')),
    ('', config('ADMIN_EMAIL_2')),
    ('', config('ADMIN_EMAIL_3')),
]
MANAGERS = ADMINS
SERVER_EMAIL = EMAIL_HOST_USER
EMAIL_SUBJECT_PREFIX = '[Aorbo Treks Error Message] '

DEFAULT_EXCEPTION_REPORTER_FILTER = 'aorbo_project.reporter_filter.MinimalExceptionReporterFilter'
DEFAULT_EXCEPTION_REPORTER = 'aorbo_project.reporter_filter.MinimalExceptionReporter'

OSM_DRAFT_NOTIFICATION_EMAILS = [
    "hello@aorbotreks.com",
    

]


LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    }
}

REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        # DEBUG mode: Relaxed limits for development
        # PRODUCTION mode: Strict limits for security
        'anon': '10000/hour' if DEBUG else '1000/hour',  # 10,000/hour in DEBUG, 1000/hour in production
        'user': '50000/hour' if DEBUG else '1000/hour',  # 50,000/hour in DEBUG, 1,000/hour in production
        'osm_draft_create': '60/hour',
        'ai_enrich': '20/hour',
        'contact_submit': '5/hour',
        'log_click': '200/hour',
        'crash_report': '100/hour',
    }
}

CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'base-uri': ("'self'",),
        'connect-src': (
            "'self'",
            'https://aorbotreks.com',
            'https://www.aorbotreks.com',
            'https://www.google.com',
            'https://www.gstatic.com',

            'https://www.google-analytics.com',
            'https://cdn.jsdelivr.net',
            'https://cdnjs.cloudflare.com',
            'http://localhost:5173',

            'http://127.0.0.1:5173',
            'http://localhost:8000',
            'http://127.0.0.1:8000',
        ),
        'default-src': (
            "'self'",
            'https://fonts.googleapis.com',
            'https://fonts.gstatic.com',
            'https://cdn.jsdelivr.net',
            'https://cdnjs.cloudflare.com',
            'https://aorbotreks.com',
            'https://www.aorbotreks.com',
            'http://localhost:5173',
            'http://127.0.0.1:5173',
            'http://localhost:8000',
            'http://127.0.0.1:8000',
        ),
        'font-src': (
            "'self'",
            'https://fonts.gstatic.com',
            'https://cdn.jsdelivr.net',
            'https://aorbotreks.com',
            'https://www.aorbotreks.com',
        ),
        'form-action': ("'self'",),
        'frame-ancestors': ("'none'",),
        'frame-src': (
            "'self'",
            'https://www.google.com',
        ),
        'img-src': (
            "'self'",
            'data:',
            'https://aorbotreks.com',
            'https://www.aorbotreks.com',
            "https://xsconhhzyaiowokwsqne.supabase.co",
            'https://www.gstatic.com',
            'https://upload.wikimedia.org',
            'http://localhost:8000',
            'http://127.0.0.1:8000',
            'http://localhost:5173',
            'http://127.0.0.1:5173',
        ),
        'object-src': ("'none'",),
        'script-src': (
            "'self'",
            "'unsafe-inline'",
            'https://cdn.jsdelivr.net',
            'https://cdnjs.cloudflare.com',
            'https://www.google.com',
            'https://www.gstatic.com',
            'https://www.googletagmanager.com',
            'https://aorbotreks.com',
            'https://www.aorbotreks.com',
        ),
        'script-src-elem': (
            "'self'",
            "'unsafe-inline'",
            'https://cdn.jsdelivr.net',
            'https://cdnjs.cloudflare.com',
            'https://www.google.com',
            'https://www.gstatic.com',
            'https://www.googletagmanager.com',
            'https://aorbotreks.com',
            'https://www.aorbotreks.com',
        ),
        'style-src': (
            "'self'",
            "'unsafe-inline'",
            'https://fonts.googleapis.com',
            'https://cdn.jsdelivr.net',
            'https://www.gstatic.com',
            'https://aorbotreks.com',
            'https://www.aorbotreks.com',
        ),
    }
}

if DEBUG:
    for directive in ["script-src", "style-src", "img-src", "font-src", "connect-src"]:
        if directive in CONTENT_SECURITY_POLICY["DIRECTIVES"]:
            CONTENT_SECURITY_POLICY["DIRECTIVES"][directive] += (
                "http://localhost:8000",
                "http://127.0.0.1:8000",
                "http://localhost:5173",
                "http://127.0.0.1:5173",
            )

# Every module's `logging.getLogger(__name__)` call reaches these handlers by
# default (root logger) - console always, plus a rotating file so errors
# from any file survive past the terminal scrollback. CrashReport rows (see
# treks_app.middleware / api_crash_report) are the queryable, DB-backed
# complement to this file log, not a replacement for it.
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'app.log',
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

