"""
Django settings for aorbo_project.

Generated by 'django-admin startproject' using Django 5.0.1.
For more information, see https://docs.djangoproject.com/en/5.0/topics/settings/
"""

import os
from pathlib import Path
import sys
from decouple import config

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = config('SECRET_KEY')

DEBUG = config('DEBUG', default='False', cast=lambda x: x.lower() in ('true', '1', 'yes'))

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1,16.170.247.251',
    cast=lambda x: [i.strip() for i in x.split(',')]
)

CSRF_TRUSTED_ORIGINS = [
    "https://aorbotreks.com",
    "https://www.aorbotreks.com",
]

if DEBUG:
    CSRF_TRUSTED_ORIGINS += [
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ]

# HSTS prevents downgrade attacks, X-Frame prevents clickjacking, etc.
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
REFERRER_POLICY = 'strict-origin-when-cross-origin'
X_FRAME_OPTIONS = 'DENY'

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

SESSION_COOKIE_HTTPONLY = True
# 'Lax' so the Django admin session cookie is sent on same-site fetches
# through the Vite dev proxy (localhost:5173 -> localhost:8000) while still
# blocking cross-site POST/CSRF usage. 'Strict' was preventing the cookie
# from being attached to the React admin dashboard's fetch() requests.
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# In DEBUG (local dev), the Vite dev server (localhost:5173) proxies /api
# requests to Django (localhost:8000). The browser treats those as a different
# "site" because the port differs, so the host-only session cookie (set for
# localhost:8000) is NOT sent — causing the admin dashboard to see an
# unauthenticated request and return JSON 403. Setting the cookie domain to
# 'localhost' makes it shared across ALL localhost ports, so the browser sends
# it when the SPA calls /api through the Vite proxy. This is dev-only; in
# production the SPA is served cookie same-origin so no domain override is
# needed (and must NOT be set, or it would break the production domain).
if DEBUG:
    SESSION_COOKIE_DOMAIN = 'localhost'
    CSRF_COOKIE_DOMAIN = 'localhost'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'corsheaders',
    'rest_framework',
    'csp',
    'axes',
    'treks_app',
    'ckeditor',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
    'axes.middleware.AxesMiddleware',
]

# CORS
CORS_ORIGIN_ALLOW_ALL = False

CORS_ALLOWED_ORIGINS = [
    "https://aorbotreks.com",
    "https://www.aorbotreks.com",
]

if DEBUG:
    CORS_ALLOWED_ORIGINS += [
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ]

CORS_ALLOW_CREDENTIALS = True

# Rate limiting with django-axes
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1
AXES_LOCKOUT_TEMPLATE = None
AXES_LOCKOUT_URL = '/accounts/lockout/'
AXES_IP_WHITELIST = []
AXES_ENABLE_ACCESS_LOG = True

ROOT_URLCONF = 'aorbo_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aorbo_project.wsgi.application'

# Database - Supabase PostgreSQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}

if not DEBUG and 'runserver' not in sys.argv:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

PASSWORD_RESET_FORM = 'treks_app.forms.CustomPasswordResetForm'

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT", cast=int)
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

OSM_DRAFT_NOTIFICATION_EMAILS = [
    "hello@aorbotreks.com",
    

]


LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        # DEBUG mode: Relaxed limits for development
        # PRODUCTION mode: Strict limits for security
        'anon': '10000/hour' if DEBUG else '100/hour',  # 10,000/hour in DEBUG, 100/hour in production
        'user': '50000/hour' if DEBUG else '1000/hour'  # 50,000/hour in DEBUG, 1,000/hour in production
    }
}

CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'base-uri': ("'self'",),
        'connect-src': (
            "'self'",
            'https://aorbotreks.com',
            'https://www.aorbotreks.com',
            'https://www.google.com',
            'https://www.gstatic.com',

            'https://www.google-analytics.com',
            'https://cdn.jsdelivr.net',
            'https://cdnjs.cloudflare.com',
            'http://localhost:5173',

            'http://127.0.0.1:5173',
            'http://localhost:8000',
            'http://127.0.0.1:8000',
        ),
        'default-src': (
            "'self'",
            'https://fonts.googleapis.com',
            'https://fonts.gstatic.com',
            'https://cdn.jsdelivr.net',
            'https://cdnjs.cloudflare.com',
            'https://aorbotreks.com',
            'https://www.aorbotreks.com',
            'http://localhost:5173',
            'http://127.0.0.1:5173',
            'http://localhost:8000',
            'http://127.0.0.1:8000',
        ),
        'font-src': (
            "'self'",
            'https://fonts.gstatic.com',
            'https://cdn.jsdelivr.net',
            'https://aorbotreks.com',
            'https://www.aorbotreks.com',
        ),
        'form-action': ("'self'",),
        'frame-ancestors': ("'none'",),
        'frame-src': (
            "'self'",
            'https://www.google.com',
        ),
        'img-src': (
            "'self'",
            'data:',
            'https://aorbotreks.com',
            'https://www.aorbotreks.com',
            "https://xsconhhzyaiowokwsqne.supabase.co",
            'https://www.gstatic.com',
            'https://upload.wikimedia.org',
            'http://localhost:8000',
            'http://127.0.0.1:8000',
            'http://localhost:5173',
            'http://127.0.0.1:5173',
        ),
        'object-src': ("'none'",),
        'script-src': (
            "'self'",
            "'unsafe-inline'",
            'https://cdn.jsdelivr.net',
            'https://cdnjs.cloudflare.com',
            'https://www.google.com',
            'https://www.gstatic.com',
            'https://www.googletagmanager.com',
            'https://aorbotreks.com',
            'https://www.aorbotreks.com',
        ),
        'script-src-elem': (
            "'self'",
            "'unsafe-inline'",
            'https://cdn.jsdelivr.net',
            'https://cdnjs.cloudflare.com',
            'https://www.google.com',
            'https://www.gstatic.com',
            'https://www.googletagmanager.com',
            'https://aorbotreks.com',
            'https://www.aorbotreks.com',
        ),
        'style-src': (
            "'self'",
            "'unsafe-inline'",
            'https://fonts.googleapis.com',
            'https://cdn.jsdelivr.net',
            'https://www.gstatic.com',
            'https://aorbotreks.com',
            'https://www.aorbotreks.com',
        ),
    }
}

if DEBUG:
    for directive in ["script-src", "style-src", "img-src", "font-src", "connect-src"]:
        if directive in CONTENT_SECURITY_POLICY["DIRECTIVES"]:
            CONTENT_SECURITY_POLICY["DIRECTIVES"][directive] += (
                "http://localhost:8000",
                "http://127.0.0.1:8000",
                "http://localhost:5173",
                "http://127.0.0.1:5173",
            )

SIMPLE_JWT = {
    'TOKEN_OBTAIN_PAIR_SERIALIZER': 'aorbo_project.serializers.MyTokenObtainPairSerializer',
}